In [38]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sym
A1 = np.array([[1,2,3,4,6],[3,4,1,6,7],[2,3,4,5,1],[1,5,0,2,8],[5,6,2,1,4]])
A1

array([[1, 2, 3, 4, 6],
       [3, 4, 1, 6, 7],
       [2, 3, 4, 5, 1],
       [1, 5, 0, 2, 8],
       [5, 6, 2, 1, 4]])

In [41]:
# транспонируем матрицу
A1.transpose()

array([[1, 3, 2, 1, 5],
       [2, 4, 3, 5, 6],
       [3, 1, 4, 0, 2],
       [4, 6, 5, 2, 1],
       [6, 7, 1, 8, 4]])

In [42]:
# найдем определитель матрицы
np.linalg.det(A1)

1748.0

In [40]:
# определитель получилcя не нулевой, значит можем найти обратную матрицу
np.linalg.inv(A1)

array([[ 0.0875286 ,  0.19851259, -0.22368421, -0.31979405,  0.21681922],
       [-0.27173913, -0.11956522,  0.25      ,  0.29347826, -0.0326087 ],
       [ 0.27860412, -0.23741419,  0.06578947, -0.04405034,  0.06922197],
       [-0.13329519,  0.18135011,  0.11842105, -0.0097254 , -0.12757437],
       [ 0.19221968,  0.00457666, -0.15789474, -0.01601831,  0.02517162]])

In [53]:
# определим ранг
np.linalg.matrix_rank(A1)


5

In [54]:
# определим собственные значения
np.linalg.eig(A1)

(array([17.75822893+0.j        ,  1.47806224+2.23891839j,
         1.47806224-2.23891839j, -2.8571767 +2.3479179j ,
        -2.8571767 -2.3479179j ]),
 array([[ 0.40210831+0.j        ,  0.12012259-0.33112571j,
          0.12012259+0.33112571j,  0.39428419-0.23933305j,
          0.39428419+0.23933305j],
        [ 0.54227897+0.j        , -0.19223905+0.36848161j,
         -0.19223905-0.36848161j, -0.17036738-0.38075154j,
         -0.17036738+0.38075154j],
        [ 0.36882788+0.j        ,  0.68026579+0.j        ,
          0.68026579-0.j        , -0.37878971+0.04663815j,
         -0.37878971-0.04663815j],
        [ 0.4351003 +0.j        , -0.28527563+0.27328901j,
         -0.28527563-0.27328901j,  0.49017464+0.j        ,
          0.49017464-0.j        ],
        [ 0.46786338+0.j        ,  0.04726212-0.28657888j,
          0.04726212+0.28657888j, -0.24041402+0.41174757j,
         -0.24041402-0.41174757j]]))

In [47]:
# создадим диагональную матрицу
I = np.eye(4)
A2 = np.array([[1,2,3,4],[2,3,4,5],[0,1,2,3],[4,3,2,1]])
A_diag = I*A2
A_diag

array([[1., 0., 0., 0.],
       [0., 3., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 1.]])

In [55]:
# определим ранг

np.linalg.matrix_rank(A_diag)


4

In [56]:
# определим собственные значения
np.linalg.eig(A_diag)

(array([1., 3., 2., 1.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [57]:
# найдем определитель матрицы
np.linalg.det(A_diag)

6.0

In [48]:
#создадим нулевую матрицу
A_Z = np.zeros([4,4])
A_Z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [58]:
# определим ранг

np.linalg.matrix_rank(A_Z)


0

In [59]:
# определим собственные значения
np.linalg.eig(A_Z)

(array([0., 0., 0., 0.]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

In [60]:
# найдем определитель матрицы
np.linalg.det(A_Z)

0.0